server:
  port: 8090

#spring整合数据源 最快的数据源
spring:
  datasource:
    #使用高版本驱动时使用cj
    #serverTimezone=GMT%2B8   东8区   %2B +号
    #&useUnicode=true&characterEncoding=utf8 是否开启unicode编码/utf-8
    #&autoReconnect=true  断线是否重连
    #&allowMultiQueries=true 是否允许批量操作
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/emp?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    #如果密码以数字0开头,则使用""号包裹  "0123456"
    password: root

#SpringBoot整合Mybatis配置
mybatis:
  #设置别名包
  type-aliases-package: org.hopesoft.pojo
  #加载映射文件
  mapper-locations: classpath:/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true